version: '3.8'
services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-container
#    environment:
#      MYSQL_ROOT_PASSWORD: Fire
#      MYSQL_DATABASE: restaurant
#      MYSQL_USER: root
#      MYSQL_PASSWORD: Fire
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
#    depends_on:
#      - mysql
    ports:
      - "8085:8085"


#volumes:
#  mysql_data:
